openapi: 3.0.0
info:
  title: Team 33H API
  version: 0.0.1
  description: The API docs for Team 33H
paths:
  /api/v1/user/register:
    post:
      tags:
        - Authentication
      description: Creates a new user account
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
            example:
              firstName: John
              lastName: Doe
              email: John@example.com
              password: Password@1
              mobilePhoneNumber: 75201514
              identityNumber: 895637943
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  id:
                    type: string
                example:
                  id: 5f521a4c68f00ed2b66b427a
        "400":
          $ref: "#/components/responses/GenericError"
  /api/v1/user/signin:
    post:
      tags:
        - Authentication
      description: Get User authentication token
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                email:
                  type: string
                password:
                  type: string
              example:
                email: john@example.com
                password: Password@1
      responses:
        "200":
          description: Authentication token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        "400":
          $ref: "#/components/responses/GenericError"
  /api/v1/user/reset-password:
    post:
      tags:
        - Authentication
      description: Ok
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                email:
                  type: string
                oldPassword:
                  type: string
                newPassword:
                  type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
        "400":
          $ref: "#/components/responses/GenericError"
  /api/v1/wallet/create:
    post:
      tags:
        - Wallet
      description: add a new wallet
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schema/Wallet"
            example:
              id: 5f521a4c68f00ed2b66b427a
              accountNumber: 12348383883
              address: "Private Bag ccc, Gabs, BW"
              firstName: John
              lastName: Doe
              deposit: 300
      responses:
        "200":
          description: account number
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  accountNumber:
                    type: number
        "400":
          $ref: "#/components/responses/GenericError"
  /api/v1/wallet/balance:
    get:
      tags:
        - Wallet
      description: retrieve wallet information
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                id:
                  type: string
            example:
              accountNumber: 12348383883
      responses:
        "200":
          description: A wallet object
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  id:
                    type: string
                  accountNumber:
                    type: number
                  address:
                    type: string
                  firstName:
                    type: string
                  lastName:
                    type: string
                  balance:
                    type: number
        "400":
          $ref: "#/components/responses/GenericError"
  /api/v1/transactions/history:
    get:
      tags:
        - Transactions
      description: retrieve wallet transactions history
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                id:
                  type: string
            example:
              accountNumber: 12348383883
      responses:
        "200":
          description: An array list of transaction
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transaction"
                
        "400":
          $ref: "#/components/responses/GenericError"
components:
  schemas:
    User:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
          format: password
        mobilePhoneNumber:
          type: number
        identityNumber:
          type: number
    Wallet:
      type: object
      properties:
        id:
          type: string
        accountNumber:
          type: number
        address:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        deposit:
          type: number
    Transaction:
      type: object
      properties:
        id:
          type: string
        wallet:
          type: object
          properties:
            accountNumber:
              type: number
        credit:
          type: object
          properties:
            accountNumber:
              type: number
            bankName:
              type: string
            reference:
              type: string
        debit:
          type: object
          properties:
            accountNumber:
              type: number
            bankName:
              type: string
            reference:
              type: string
    Error:
      type: object
      properties:
        error:
          type: string
  responses:
    GenericError:
      description: Error object
      content:
        application/json:
          schema:
            "$ref": "#/components/schemas/Error"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
